podTemplate(cloud: 'kubernetes', label: 'terraform', yaml: template) {
    node ("terraform") {
        container("terraform") {
            stage ("Pull code") {
                git branch: 'main', url: 'https://github.com/svalovtech/jenkins-april-2024.git'
            }

            stage ("Write tfvars") {
                writeFile file: 'terraform.tfvars', text: """
                ami_id = "${params.ami_id}"
                region = "${params.region}"
                """
            }

            withCredentials([usernamePassword(credentialsId: 'aws-creds', passwordVariable: 'AWS_SECRET_ACCESS_KEY', usernameVariable: 'AWS_ACCESS_KEY_ID')]) {
                stage ("Init") {
                    sh """
                    cd terraform
                    terraform init
                    """
                }

                if (params.action == "apply") {
                    stage ("Plan") {
                        sh """
                        cd terraform
                        terraform plan -out=tfplan -var-file=terraform.tfvars
                        """
                    }

                    stage ("Apply") {
                        sh """
                        cd terraform
                        terraform apply -auto-approve -var-file=terraform.tfvars tfplan
                        """
                    }
                } else {
                    stage ("Destroy") {
                        sh """
                        cd terraform
                        terraform destroy -auto-approve -var-file=terraform.tfvars
                        """
                    }
                }
            }
        }
    }
}
